# basic options
title: Test website
author: Milkshake
email: your-email@domain.com
# description: A wonderful site
twitter_username: jekyllrb
facebook_username: jekyll
# github_username:  jekyll

# Build settings
#markdown: kramdown
theme: minima
